# Generated by Django 6.0.6 on 2026-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
