# Generated by Django 6.0.6 on 2026-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_codigo_barras_producto_codigo_barras_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_oferta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
