# Generated by Django 6.0.6 on 2026-07-08 20:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        ('productos', '0002_producto_costo_producto_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='percepcion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='GastoBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='gastos.gasto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
