# Generated by Django 6.0.6 on 2026-07-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gasto_percepcion_gastobonificacion'),
        ('productos', '0002_producto_costo_producto_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
