# Generated by Django 6.0.6 on 2026-08-06 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_gastoitem_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
