# Generated by Django 6.0.6 on 2026-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_alter_gastoitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='gastos/'),
        ),
    ]
