# Generated by Django 6.0.6 on 2026-08-13 19:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gasto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static\\img\\boletas/', location='C:\\Users\\alan_\\OneDrive\\Escritorio\\SistemaBodega\\bodega\\static\\img\\boletas'), upload_to=''),
        ),
    ]
