# Generated by Django 6.0.6 on 2026-06-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_compra',
            field=models.CharField(choices=[('yape', 'Yape'), ('efectivo', 'Efectivo'), ('fiado', 'Fiado')], default='efectivo', max_length=20),
        ),
    ]
