# Generated by Django 6.0.6 on 2026-07-14 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_compra_cliente_compra_tipo_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
    ]
