# Generated by Django 6.0.6 on 2026-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_compra_adicional_compra_descuento_compra_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
