# Generated by Django 6.0.6 on 2026-08-13 20:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_compra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dinero_recibido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
